/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'save-resume': ApiRouteHandler<{ userId: string; title: string; templateKey: string; data: { personal: { fullName: string; title: string; email: string; phone: string; website?: string; github?: string; linkedin?: string; location: string; image?: string }; summary?: string; skills: { name: string }[]; experience: { jobTitle: string; company: string; location?: string; startDate: string; endDate: string; details: string; isCurrent?: boolean }[]; education: { degree: string; school: string; location?: string; startDate: string; endDate: string; details?: string }[]; projects?: { title: string; description: string; technologies?: string[]; link?: string; date?: string }[]; certifications?: { name: string; issuer?: string; dateEarned?: string }[]; mentorship?: { title: string; description: string; date?: string }[]; languages?: { name: string; proficiency?: string }[] } }, unknown, never>
    'get-user-resumes': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'register-user': ApiRouteHandler<{ name: string; email: string; password: string }, unknown, never>
    'login-user': ApiRouteHandler<{ email: string; password: string }, unknown, never>
    'get-user': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
}